package VO.Model;
// Generated 07/11/2015 23:58:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Atividadehistorico generated by hbm2java
 */
public class Atividadehistorico  implements java.io.Serializable {


     private int id;
     private Atividade atividade;
     private Funcionario funcionario;
     private Sitatividade sitatividade;
     private String descricao;
     private Date dtalteracao;
     private Boolean isAtual;

    public Atividadehistorico() {
    }

	
    public Atividadehistorico(int id) {
        this.id = id;
    }
    public Atividadehistorico(int id, Atividade atividade, Funcionario funcionario, Sitatividade sitatividade, String descricao, Date dtalteracao, Boolean isAtual) {
       this.id = id;
       this.atividade = atividade;
       this.funcionario = funcionario;
       this.sitatividade = sitatividade;
       this.descricao = descricao;
       this.dtalteracao = dtalteracao;
       this.isAtual = isAtual;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Atividade getAtividade() {
        return this.atividade;
    }
    
    public void setAtividade(Atividade atividade) {
        this.atividade = atividade;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Sitatividade getSitatividade() {
        return this.sitatividade;
    }
    
    public void setSitatividade(Sitatividade sitatividade) {
        this.sitatividade = sitatividade;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getDtalteracao() {
        return this.dtalteracao;
    }
    
    public void setDtalteracao(Date dtalteracao) {
        this.dtalteracao = dtalteracao;
    }
    public Boolean getIsAtual() {
        return this.isAtual;
    }
    
    public void setIsAtual(Boolean isAtual) {
        this.isAtual = isAtual;
    }




}


