package VO.Model;
// Generated 20/11/2015 17:23:36 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Atividade generated by hbm2java
 */
public class Atividade  implements java.io.Serializable {


     private int id;
     private Funcionarioprojeto funcionarioprojeto;
     private Sitatividade sitatividade;
     private Sprint sprint;
     private Tpprioridade tpprioridade;
     private Tptempo tptempoByTptempoconclusaoid;
     private Tptempo tptempoByTptempoestimadoid;
     private String nome;
     private Date dtcriacao;
     private String descricao;
     private Date dtalteracao;
     private String descconclusao;

    public Atividade() {
    }

	
    public Atividade(int id, Sprint sprint) {
        this.id = id;
        this.sprint = sprint;
    }
    public Atividade(int id, Funcionarioprojeto funcionarioprojeto, Sitatividade sitatividade, Sprint sprint, Tpprioridade tpprioridade, Tptempo tptempoByTptempoconclusaoid, Tptempo tptempoByTptempoestimadoid, String nome, Date dtcriacao, String descricao, Date dtalteracao, String descconclusao) {
       this.id = id;
       this.funcionarioprojeto = funcionarioprojeto;
       this.sitatividade = sitatividade;
       this.sprint = sprint;
       this.tpprioridade = tpprioridade;
       this.tptempoByTptempoconclusaoid = tptempoByTptempoconclusaoid;
       this.tptempoByTptempoestimadoid = tptempoByTptempoestimadoid;
       this.nome = nome;
       this.dtcriacao = dtcriacao;
       this.descricao = descricao;
       this.dtalteracao = dtalteracao;
       this.descconclusao = descconclusao;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Funcionarioprojeto getFuncionarioprojeto() {
        return this.funcionarioprojeto;
    }
    
    public void setFuncionarioprojeto(Funcionarioprojeto funcionarioprojeto) {
        this.funcionarioprojeto = funcionarioprojeto;
    }
    public Sitatividade getSitatividade() {
        return this.sitatividade;
    }
    
    public void setSitatividade(Sitatividade sitatividade) {
        this.sitatividade = sitatividade;
    }
    public Sprint getSprint() {
        return this.sprint;
    }
    
    public void setSprint(Sprint sprint) {
        this.sprint = sprint;
    }
    public Tpprioridade getTpprioridade() {
        return this.tpprioridade;
    }
    
    public void setTpprioridade(Tpprioridade tpprioridade) {
        this.tpprioridade = tpprioridade;
    }
    public Tptempo getTptempoByTptempoconclusaoid() {
        return this.tptempoByTptempoconclusaoid;
    }
    
    public void setTptempoByTptempoconclusaoid(Tptempo tptempoByTptempoconclusaoid) {
        this.tptempoByTptempoconclusaoid = tptempoByTptempoconclusaoid;
    }
    public Tptempo getTptempoByTptempoestimadoid() {
        return this.tptempoByTptempoestimadoid;
    }
    
    public void setTptempoByTptempoestimadoid(Tptempo tptempoByTptempoestimadoid) {
        this.tptempoByTptempoestimadoid = tptempoByTptempoestimadoid;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getDtcriacao() {
        return this.dtcriacao;
    }
    
    public void setDtcriacao(Date dtcriacao) {
        this.dtcriacao = dtcriacao;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getDtalteracao() {
        return this.dtalteracao;
    }
    
    public void setDtalteracao(Date dtalteracao) {
        this.dtalteracao = dtalteracao;
    }
    public String getDescconclusao() {
        return this.descconclusao;
    }
    
    public void setDescconclusao(String descconclusao) {
        this.descconclusao = descconclusao;
    }




}


