package VO.Model;
// Generated 07/11/2015 23:58:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Atividade generated by hbm2java
 */
public class Atividade  implements java.io.Serializable {


     private int id;
     private Sprint sprint;
     private Tpprioridade tpprioridade;
     private String nome;
     private Date dtcriacao;
     private Set atividadehistoricos = new HashSet(0);
     private Set atividadefuncionarios = new HashSet(0);

    public Atividade() {
    }

	
    public Atividade(int id, Sprint sprint) {
        this.id = id;
        this.sprint = sprint;
    }
    public Atividade(int id, Sprint sprint, Tpprioridade tpprioridade, String nome, Date dtcriacao, Set atividadehistoricos, Set atividadefuncionarios) {
       this.id = id;
       this.sprint = sprint;
       this.tpprioridade = tpprioridade;
       this.nome = nome;
       this.dtcriacao = dtcriacao;
       this.atividadehistoricos = atividadehistoricos;
       this.atividadefuncionarios = atividadefuncionarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Sprint getSprint() {
        return this.sprint;
    }
    
    public void setSprint(Sprint sprint) {
        this.sprint = sprint;
    }
    public Tpprioridade getTpprioridade() {
        return this.tpprioridade;
    }
    
    public void setTpprioridade(Tpprioridade tpprioridade) {
        this.tpprioridade = tpprioridade;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getDtcriacao() {
        return this.dtcriacao;
    }
    
    public void setDtcriacao(Date dtcriacao) {
        this.dtcriacao = dtcriacao;
    }
    public Set getAtividadehistoricos() {
        return this.atividadehistoricos;
    }
    
    public void setAtividadehistoricos(Set atividadehistoricos) {
        this.atividadehistoricos = atividadehistoricos;
    }
    public Set getAtividadefuncionarios() {
        return this.atividadefuncionarios;
    }
    
    public void setAtividadefuncionarios(Set atividadefuncionarios) {
        this.atividadefuncionarios = atividadefuncionarios;
    }




}


