package VO.Model;
// Generated 20/11/2015 17:23:36 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private int id;
     private Tpcargo tpcargo;
     private String nome;
     private String sobrenome;
     private String email;
     private String password;
     private String imgperfil;
     private Date dtcriacao;
     private Boolean isAtivo;
     private Set funcionarioprojetos = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(int id) {
        this.id = id;
    }
    public Funcionario(int id, Tpcargo tpcargo, String nome, String sobrenome, String email, String password, Date dtcriacao, Boolean isAtivo, Set funcionarioprojetos) {
       this.id = id;
       this.tpcargo = tpcargo;
       this.nome = nome;
       this.sobrenome = sobrenome;
       this.email = email;
       this.password = password;
       this.dtcriacao = dtcriacao;
       this.isAtivo = isAtivo;
       this.funcionarioprojetos = funcionarioprojetos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Tpcargo getTpcargo() {
        return this.tpcargo;
    }
    
    public void setTpcargo(Tpcargo tpcargo) {
        this.tpcargo = tpcargo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getDtcriacao() {
        return this.dtcriacao;
    }
    
    public void setDtcriacao(Date dtcriacao) {
        this.dtcriacao = dtcriacao;
    }
    public Boolean getIsAtivo() {
        return this.isAtivo;
    }
    
    public void setIsAtivo(Boolean isAtivo) {
        this.isAtivo = isAtivo;
    }
    public Set getFuncionarioprojetos() {
        return this.funcionarioprojetos;
    }
    
    public void setFuncionarioprojetos(Set funcionarioprojetos) {
        this.funcionarioprojetos = funcionarioprojetos;
    }

    public String getImgperfil() {
        return imgperfil;
    }

    public void setImgperfil(String imgperfil) {
        this.imgperfil = imgperfil;
    }




}


