package VO.Model;
// Generated 10/11/2015 14:22:55 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Funcionarioprojeto generated by hbm2java
 */
public class Funcionarioprojeto  implements java.io.Serializable {


     private int id;
     private Funcionario funcionario;
     private Projeto projeto;
     private Boolean isAdm;
     private Date dtcriacao;
     private Date dtalteracao;
     private Boolean isAtivo;

    public Funcionarioprojeto() {
    }

	
    public Funcionarioprojeto(int id, Funcionario funcionario, Projeto projeto) {
        this.id = id;
        this.funcionario = funcionario;
        this.projeto = projeto;
    }
    public Funcionarioprojeto(int id, Funcionario funcionario, Projeto projeto, Boolean isAdm, Date dtcriacao, Date dtalteracao, Boolean isAtivo) {
       this.id = id;
       this.funcionario = funcionario;
       this.projeto = projeto;
       this.isAdm = isAdm;
       this.dtcriacao = dtcriacao;
       this.dtalteracao = dtalteracao;
       this.isAtivo = isAtivo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Projeto getProjeto() {
        return this.projeto;
    }
    
    public void setProjeto(Projeto projeto) {
        this.projeto = projeto;
    }
    public Boolean getIsAdm() {
        return this.isAdm;
    }
    
    public void setIsAdm(Boolean isAdm) {
        this.isAdm = isAdm;
    }
    public Date getDtcriacao() {
        return this.dtcriacao;
    }
    
    public void setDtcriacao(Date dtcriacao) {
        this.dtcriacao = dtcriacao;
    }
    public Date getDtalteracao() {
        return this.dtalteracao;
    }
    
    public void setDtalteracao(Date dtalteracao) {
        this.dtalteracao = dtalteracao;
    }
    public Boolean getIsAtivo() {
        return this.isAtivo;
    }
    
    public void setIsAtivo(Boolean isAtivo) {
        this.isAtivo = isAtivo;
    }




}


