package VO.Model;
// Generated 20/11/2015 17:23:36 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Projeto generated by hbm2java
 */
public class Projeto  implements java.io.Serializable {


     private int id;
     private Sitprojeto sitprojeto;
     private String nome;
     private String descricao;
     private Date dtcriacao;
     private Date dtalteracao;
     private Funcionario usercriador;
     private Set funcionarioprojetos = new HashSet(0);
     private Set sprints = new HashSet(0);

    public Projeto() {
    }

	
    public Projeto(int id) {
        this.id = id;
    }
    public Projeto(int id, Sitprojeto sitprojeto, String nome, String descricao, Date dtcriacao, Date dtalteracao, Set funcionarioprojetos, Set sprints) {
       this.id = id;
       this.sitprojeto = sitprojeto;
       this.nome = nome;
       this.descricao = descricao;
       this.dtcriacao = dtcriacao;
       this.dtalteracao = dtalteracao;
       this.funcionarioprojetos = funcionarioprojetos;
       this.sprints = sprints;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Sitprojeto getSitprojeto() {
        return this.sitprojeto;
    }
    
    public void setSitprojeto(Sitprojeto sitprojeto) {
        this.sitprojeto = sitprojeto;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getDtcriacao() {
        return this.dtcriacao;
    }
    
    public void setDtcriacao(Date dtcriacao) {
        this.dtcriacao = dtcriacao;
    }
    public Date getDtalteracao() {
        return this.dtalteracao;
    }
    
    public void setDtalteracao(Date dtalteracao) {
        this.dtalteracao = dtalteracao;
    }
    public Set getFuncionarioprojetos() {
        return this.funcionarioprojetos;
    }
    
    public void setFuncionarioprojetos(Set funcionarioprojetos) {
        this.funcionarioprojetos = funcionarioprojetos;
    }
    public Set getSprints() {
        return this.sprints;
    }
    
    public void setSprints(Set sprints) {
        this.sprints = sprints;
    }

    public Funcionario getUsercriador() {
        return usercriador;
    }

    public void setUsercriador(Funcionario usercriador) {
        this.usercriador = usercriador;
    }




}


