package VO.Model;
// Generated 07/11/2015 23:58:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sitatividade generated by hbm2java
 */
public class Sitatividade  implements java.io.Serializable {


     private int id;
     private String label;
     private Integer order;
     private Boolean isAtivo;
     private Set atividadehistoricos = new HashSet(0);

    public Sitatividade() {
    }

	
    public Sitatividade(int id) {
        this.id = id;
    }
    public Sitatividade(int id, String label, Integer order, Boolean isAtivo, Set atividadehistoricos) {
       this.id = id;
       this.label = label;
       this.order = order;
       this.isAtivo = isAtivo;
       this.atividadehistoricos = atividadehistoricos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
    public Integer getOrder() {
        return this.order;
    }
    
    public void setOrder(Integer order) {
        this.order = order;
    }
    public Boolean getIsAtivo() {
        return this.isAtivo;
    }
    
    public void setIsAtivo(Boolean isAtivo) {
        this.isAtivo = isAtivo;
    }
    public Set getAtividadehistoricos() {
        return this.atividadehistoricos;
    }
    
    public void setAtividadehistoricos(Set atividadehistoricos) {
        this.atividadehistoricos = atividadehistoricos;
    }




}


