package VO.Dados;
// Generated 07/11/2015 19:10:52 by Hibernate Tools 4.3.1



/**
 * FuncionarioprojetoId generated by hbm2java
 */
public class FuncionarioprojetoId  implements java.io.Serializable {


     private int id;
     private int funcionarioid;
     private int projetoid;

    public FuncionarioprojetoId() {
    }

    public FuncionarioprojetoId(int id, int funcionarioid, int projetoid) {
       this.id = id;
       this.funcionarioid = funcionarioid;
       this.projetoid = projetoid;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getFuncionarioid() {
        return this.funcionarioid;
    }
    
    public void setFuncionarioid(int funcionarioid) {
        this.funcionarioid = funcionarioid;
    }
    public int getProjetoid() {
        return this.projetoid;
    }
    
    public void setProjetoid(int projetoid) {
        this.projetoid = projetoid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FuncionarioprojetoId) ) return false;
		 FuncionarioprojetoId castOther = ( FuncionarioprojetoId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getFuncionarioid()==castOther.getFuncionarioid())
 && (this.getProjetoid()==castOther.getProjetoid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getFuncionarioid();
         result = 37 * result + this.getProjetoid();
         return result;
   }   


}


