package VO.Dados;
// Generated 07/11/2015 19:10:52 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Funcionariocargo generated by hbm2java
 */
public class Funcionariocargo  implements java.io.Serializable {


     private int id;
     private Funcionario funcionario;
     private Tpcargo tpcargo;
     private Date dtcriacao;
     private Boolean isAtual;

    public Funcionariocargo() {
    }

	
    public Funcionariocargo(int id, Funcionario funcionario, Tpcargo tpcargo) {
        this.id = id;
        this.funcionario = funcionario;
        this.tpcargo = tpcargo;
    }
    public Funcionariocargo(int id, Funcionario funcionario, Tpcargo tpcargo, Date dtcriacao, Boolean isAtual) {
       this.id = id;
       this.funcionario = funcionario;
       this.tpcargo = tpcargo;
       this.dtcriacao = dtcriacao;
       this.isAtual = isAtual;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Tpcargo getTpcargo() {
        return this.tpcargo;
    }
    
    public void setTpcargo(Tpcargo tpcargo) {
        this.tpcargo = tpcargo;
    }
    public Date getDtcriacao() {
        return this.dtcriacao;
    }
    
    public void setDtcriacao(Date dtcriacao) {
        this.dtcriacao = dtcriacao;
    }
    public Boolean getIsAtual() {
        return this.isAtual;
    }
    
    public void setIsAtual(Boolean isAtual) {
        this.isAtual = isAtual;
    }




}


