package VO.Dados;
// Generated 01/11/2015 22:01:27 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private int id;
     private String nome;
     private String sobrenome;
     private String email;
     private String password;
     private Date dtcriacao;
     private Boolean isAtivo;

    public Funcionario() {
    }

	
    public Funcionario(int id) {
        this.id = id;
    }
    public Funcionario(int id, String nome, String sobrenome, String email, String password, Date dtcriacao, Boolean isAtivo) {
       this.id = id;
       this.nome = nome;
       this.sobrenome = sobrenome;
       this.email = email;
       this.password = password;
       this.dtcriacao = dtcriacao;
       this.isAtivo = isAtivo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getDtcriacao() {
        return this.dtcriacao;
    }
    
    public void setDtcriacao(Date dtcriacao) {
        this.dtcriacao = dtcriacao;
    }
    public Boolean getIsAtivo() {
        return this.isAtivo;
    }
    
    public void setIsAtivo(Boolean isAtivo) {
        this.isAtivo = isAtivo;
    }




}


