package VO.Dados;
// Generated 07/11/2015 19:10:52 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private int id;
     private String nome;
     private String sobrenome;
     private String email;
     private String password;
     private Date dtcriacao;
     private Boolean isAtivo;
     private Set atividadehistoricos = new HashSet(0);
     private Set funcionariocargos = new HashSet(0);
     private Set funcionarioprojetos = new HashSet(0);
     private Set atividadefuncionarios = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(int id) {
        this.id = id;
    }
    public Funcionario(int id, String nome, String sobrenome, String email, String password, Date dtcriacao, Boolean isAtivo, Set atividadehistoricos, Set funcionariocargos, Set funcionarioprojetos, Set atividadefuncionarios) {
       this.id = id;
       this.nome = nome;
       this.sobrenome = sobrenome;
       this.email = email;
       this.password = password;
       this.dtcriacao = dtcriacao;
       this.isAtivo = isAtivo;
       this.atividadehistoricos = atividadehistoricos;
       this.funcionariocargos = funcionariocargos;
       this.funcionarioprojetos = funcionarioprojetos;
       this.atividadefuncionarios = atividadefuncionarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getDtcriacao() {
        return this.dtcriacao;
    }
    
    public void setDtcriacao(Date dtcriacao) {
        this.dtcriacao = dtcriacao;
    }
    public Boolean getIsAtivo() {
        return this.isAtivo;
    }
    
    public void setIsAtivo(Boolean isAtivo) {
        this.isAtivo = isAtivo;
    }
    public Set getAtividadehistoricos() {
        return this.atividadehistoricos;
    }
    
    public void setAtividadehistoricos(Set atividadehistoricos) {
        this.atividadehistoricos = atividadehistoricos;
    }
    public Set getFuncionariocargos() {
        return this.funcionariocargos;
    }
    
    public void setFuncionariocargos(Set funcionariocargos) {
        this.funcionariocargos = funcionariocargos;
    }
    public Set getFuncionarioprojetos() {
        return this.funcionarioprojetos;
    }
    
    public void setFuncionarioprojetos(Set funcionarioprojetos) {
        this.funcionarioprojetos = funcionarioprojetos;
    }
    public Set getAtividadefuncionarios() {
        return this.atividadefuncionarios;
    }
    
    public void setAtividadefuncionarios(Set atividadefuncionarios) {
        this.atividadefuncionarios = atividadefuncionarios;
    }




}


